#!/usr/bin/env bash

# https://www.knifepoint.net/~kat/kb-jj-patchedit.html
set -xev

left="$1"
right="$2"

nvim_neogit() {
  init=$(cat << EOF
-- Use <F4> to abort the split operation.
vim.keymap.set("n", "<F4>", "<cmd>cq<cr>")

-- Use cc to close the current buffer.
vim.keymap.set({"n", "v"}, "cc", "<cmd>qa!<cr>")

-- Unload Neogit to allow the custom config (see below) to apply.
package.loaded["neogit"] = nil

local neogit = require("neogit")
neogit.setup({
  disable_hint = false,
  sections = {
    -- Show new files (in this commit).
    untracked = { folded = false, hidden = false },
  },
  mappings = {
    popup = {
      -- Disable this mapping to open the commit popup thereby enabling the
      -- mapping of "c" from above.
      ["c"] = false,
    },
  },
})

-- Open Neogit immediately.
neogit.open()

-- Close the empty buffer that got opened when Neovim was started.
vim.cmd("tabclose #")
EOF
)
  nvim -c ":lua $init"
}

GBDEFJJ_EDITOR=${GBDEFJJ_EDITOR:-nvim_neogit}

(
  cd "$right"

  patch_file="$(mktemp --suffix=.patch)"

  # Prepare patch by comparing left & right.
  diff --new-file --text --unified --exclude JJ-INSTRUCTIONS --recursive "$left"/ ./ \
    >"$patch_file" || (($? == 1))

  # Un-apply patch and prepare the initial state.
  patch --reverse --strip=1 <"$patch_file"
  git init .
  git add .
  git commit -m 'orig left'

  # Re-apply and changes.
  patch --strip=1 <"$patch_file"

  # Interactively stage changes, then remove all unstaged changes.
  $GBDEFJJ_EDITOR
  git checkout .
  git clean -xfd
  rm -rf ./.git
)
