#!/usr/bin/env bash

set -e

left="$1"
right="$2"

git_add_p() {
  # We need to `add --intent-to-add` so that new files (new in the commit to be
  # diff-edited) are shown by `add -p` just below.
  git add --intent-to-add .
  git status
  git add -p
  git status
  read -r -p "Press Enter to commit."
}

nvim_neogit() {
  init=$(cat << EOF
-- Use <F4> to abort the diff-edit operation.
vim.keymap.set("n", "<F4>", "<cmd>cq<cr>")

-- Use cc to close the Neovim.
vim.keymap.set({"n", "v"}, "cc", "<cmd>qa!<cr>")

-- Unload Neogit to allow the custom config (see below) to apply.
package.loaded["neogit"] = nil

local neogit = require("neogit")
neogit.setup({
  sections = {
    -- Show new files (in this commit).
    untracked = { folded = false, hidden = false },
    -- Do not show recent commits.
    recent = { folded = true, hidden = true, },
  },
  mappings = {
    popup = {
      -- Disable the mapping to open the commit popup thereby enabling the
      -- mapping of "cc" from above which will then drop us into the commit
      -- message description of the first (Jujutsu) commit.
      ["c"] = false,
    },
  },
})

-- Open Neogit immediately.
neogit.open()

-- Close the empty buffer that got opened when Neovim was started.
vim.cmd("tabclose #")
EOF
)
  nvim -c ":lua $init"
}

GBDEFJJ_EDITOR=${GBDEFJJ_EDITOR:-nvim_neogit}

(
  cd "$left"

  # Create Git repo in $left and move only the git_dir to $right.
  # From Git's perspective, anything in $right that is not in $left is now
  # unstaged.
  git init .
  git add .
  git commit -m 'orig left' || true # should succeed even if only new files in $right
  mv .git "$right"
)

(
  cd "$right"
  rm JJ-INSTRUCTIONS

  # Interactively stage changes.
  $GBDEFJJ_EDITOR

  # Then remove all unstaged changes.
  git restore . || true # remove changes (if any)
  git clean -xfd # remove new files that have not been staged

  # Finally, remove the temporary Git repo.
  rm -rf ./.git
)
