#!/usr/bin/env bash

# https://www.knifepoint.net/~kat/kb-jj-patchedit.html
set -xev

left="$1"
right="$2"

patch_file="$(mktemp --suffix=.patch)"

nvim_neogit() {
  # Use <F4> to quit with `exit 1`, thus aborting the jj-opration completely.
  # Use <F10> to confirm, thus adding all staged changes into the first commit.
  nvim -c ':Neogit' -c ':map <F4> :cq<cr>' -c ':map <F10> :qa!<cr>'
}

GBDEFJJ_EDITOR=${GBDEFJJ_EDITOR:-nvim_neogit}

(
  cd "$right"

  # Prepare patch by comparing left & right.
  diff --new-file --text --unified --exclude JJ-INSTRUCTIONS --recursive "$left"/ ./ \
    >"$patch_file" || (($? == 1))

  # Un-apply patch and prepare the initial state.
  patch --reverse --strip=1 <"$patch_file"
  git init .
  git add .
  git commit -m 'orig left'

  # Re-apply and changes.
  patch --strip=1 <"$patch_file"

  # Interactively stage changes, then remove all unstaged changes.
  $GBDEFJJ_EDITOR
  git checkout .
  git clean -xfd
  rm -rf ./.git
)
